[2024-06-07T15:07:08.071+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T15:07:08.082+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.download manual__2024-06-07T15:07:07.176612+00:00 [queued]>
[2024-06-07T15:07:08.085+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.download manual__2024-06-07T15:07:07.176612+00:00 [queued]>
[2024-06-07T15:07:08.085+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-07T15:07:08.173+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): download> on 2024-06-07 15:07:07.176612+00:00
[2024-06-07T15:07:08.177+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T15:07:08.178+0000] {standard_task_runner.py:63} INFO - Started process 171 to run task
[2024-06-07T15:07:08.178+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'download', 'manual__2024-06-07T15:07:07.176612+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmphxbc9100']
[2024-06-07T15:07:08.179+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask download
[2024-06-07T15:07:08.199+0000] {task_command.py:426} INFO - Running <TaskInstance: LocalIngestionDag.download manual__2024-06-07T15:07:07.176612+00:00 [running]> on host cd877b1b2f1c
[2024-06-07T15:07:08.221+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-06-07T15:07:08.234+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='download' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T15:07:07.176612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-07T15:07:07.176612+00:00'
[2024-06-07T15:07:08.235+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T15:07:08.241+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-07T15:07:08.242+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz -O /opt/***/output_2024-06.csv']
[2024-06-07T15:07:08.247+0000] {subprocess.py:86} INFO - Output:
[2024-06-07T15:07:08.248+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: wget: command not found
[2024-06-07T15:07:08.248+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-06-07T15:07:08.248+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T15:07:08.253+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-06-07T15:07:08.255+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=download, run_id=manual__2024-06-07T15:07:07.176612+00:00, execution_date=20240607T150707, start_date=20240607T150708, end_date=20240607T150708
[2024-06-07T15:07:08.260+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task download (Bash command failed. The command returned a non-zero exit code 127.; 171)
[2024-06-07T15:07:08.282+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-07T15:07:08.292+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-07T15:07:08.294+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
